user                            root;
worker_processes                auto;

error_log                       /var/log/nginx/error.log warn;

events {
    worker_connections          1024;
}

http {
    add_header Access-Control-Allow-Origin *;
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    off;
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           3000;
    
    server {
        listen                  8080;
        
        gzip on;
        gzip_types text/plain application/javascript application/x-javascript application/json text/css text/javascript;

        server_name  localhost;
        root  /usr/share/nginx/html;
        include /etc/nginx/mime.types;
        
        location ~* /MF-Contenedor* {
            try_files $uri $uri/ /MF-Contenedor/index.html;
        }

        location = /MF-Contenedor/status {
        default_type application/json;
        return 200 '{ "mensaje": "Operación exitosa", "folio": "xxxxxxxxx" }';
        }
    }
    include /etc/nginx/conf.d/*.conf;
}